### ISSUE TITLE
not opening files?

### ISSUE THREAD

**Issue by mike3056** [thefifthmatt/ESDLang#1]
i put the oo2core dl in the file like it says but it still says unable to load it. I verified the game to try the new oo2core it generated and still nothing. Can it just not open the item msg? trying to add more stuff to kales shop bypassing the limit stock he has

Using config C:\Program Files (x86)\Steam\steamapps\common\ELDEN RING\Game\script\talk\m11_00_00_00-talkesdbnd-dcx\GR\data\INTERROOT_win64\script\talk\m11_00_00_00\esdtoolconfig.json

------------------------

esdtool.exe -er -basedir "C:\Program Files (x86)\Steam\steamapps\common\ELDEN RING\Game" -backup -i "C:\Program Files (x86)\Steam\steamapps\common\ELDEN RING\Game\script\talk\m11_00_00_00-talkesdbnd-dcx\GR\data\INTERROOT_win64\script\talk\m11_00_00_00\t351001100.esd" -writepy "C:\Program Files (x86)\Steam\steamapps\common\ELDEN RING\Game\script\talk\m11_00_00_00-talkesdbnd-dcx\GR\data\INTERROOT_win64\script\talk\m11_00_00_00\%e.py"

System.Exception: Failed to load C:\Program Files (x86)\Steam\steamapps\common\ELDEN RING\Game\msg\engus\item.msgbnd.dcx: System.Exception: Failed to load C:\Program Files (x86)\Steam\steamapps\common\ELDEN RING\Game\msg\engus\item.msgbnd.dcx: System.DllNotFoundException: Unable to load DLL 'oo2core_6_win64.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at SoulsFormats.Oodle26.OodleLZ_GetDecodeBufferSize(Int64 rawSize, Boolean corruptionPossible)
   at SoulsFormats.Oodle26.Decompress(Byte[] source, Int64 uncompressedSize)
   at SoulsIds.GameEditor.ReadBnd(String path)
   at SoulsIds.GameEditor.ReadBnd(String path)
   at SoulsIds.GameEditor.LoadBnd[T](String path, Func`3 parser, String fileExt)
   at SoulsIds.GameEditor.LoadBnd[T](String path, Func`3 parser, String fileExt)
   at SoulsIds.GameEditor.LoadBnds[T](String relDir, Func`3 parser, String ext, String fileExt)
   at SoulsIds.Scraper.ScrapeMsgs(Universe u)
   at ESDLang.Script.CommandRunner.Run()
   at ESDLang.Script.Program.Run(IList`1 args)
   at ESDLang.Script.Program.Main(String[] args)

Press any key to exit.

**Comment by mike3056** [comment]
never mind i was being dumb it works now lol

**Comment by gunnm730** [comment]
> never mind i was being dumb it works now lol

hey bro,sorry to bother u,but i ve met the same.i wanna learn how you solved this situation?

**Comment by gracenotes** [comment]
Belated closure. esdtool now copies oodle dll automatically, but if that doesn't work it still can be copied automatically.
